server:
  port: 3600
spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medicalsysdb?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
  mvc:
    favicon:
      enabled=false:
